// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_everything_by_design = "CgkIhpOPlaMXEAIQFg"; // <GPGSID>
        public const string achievement_almost_there = "CgkIhpOPlaMXEAIQCA"; // <GPGSID>
        public const string achievement_finir_lvl_bonus_2 = "CgkIhpOPlaMXEAIQEg"; // <GPGSID>
        public const string achievement_you_got_the_moves = "CgkIhpOPlaMXEAIQCg"; // <GPGSID>
        public const string achievement_get_50_stars = "CgkIhpOPlaMXEAIQAQ"; // <GPGSID>
        public const string achievement_perfect_3140 = "CgkIhpOPlaMXEAIQDw"; // <GPGSID>
        public const string achievement_perfect_110 = "CgkIhpOPlaMXEAIQAg"; // <GPGSID>
        public const string achievement_get_150_stars = "CgkIhpOPlaMXEAIQBQ"; // <GPGSID>
        public const string achievement_perfect_2130 = "CgkIhpOPlaMXEAIQDg"; // <GPGSID>
        public const string achievement_perfect_1120 = "CgkIhpOPlaMXEAIQDQ"; // <GPGSID>
        public const string achievement_dont_even_think_about_it = "CgkIhpOPlaMXEAIQCQ"; // <GPGSID>
        public const string achievement_finir_lvl_bonus_4 = "CgkIhpOPlaMXEAIQFA"; // <GPGSID>
        public const string achievement_travail_bnvole = "CgkIhpOPlaMXEAIQBg"; // <GPGSID>
        public const string achievement_dont_give_up__you_can_still_win_this = "CgkIhpOPlaMXEAIQCw"; // <GPGSID>
        public const string achievement_finir_lvl_bonus_1 = "CgkIhpOPlaMXEAIQEQ"; // <GPGSID>
        public const string achievement_finir_lvl_bonus_5 = "CgkIhpOPlaMXEAIQFQ"; // <GPGSID>
        public const string achievement_get_100_stars = "CgkIhpOPlaMXEAIQBA"; // <GPGSID>
        public const string achievement_congratulation__youve_won_nothing = "CgkIhpOPlaMXEAIQBw"; // <GPGSID>
        public const string achievement_not_your_business = "CgkIhpOPlaMXEAIQDA"; // <GPGSID>
        public const string achievement_finir_lvl_bonus_3 = "CgkIhpOPlaMXEAIQEw"; // <GPGSID>
        public const string achievement_first_time_here = "CgkIhpOPlaMXEAIQAw"; // <GPGSID>
        public const string achievement_perfect_4150 = "CgkIhpOPlaMXEAIQEA"; // <GPGSID>

}

